const API = 'https://ckzwmimmwdnmpohgvcka.supabase.co/functions/v1/unity-ai-office-web';
const positions = {pmo:[88,88],design:[64,38],dev:[28,58],sales:[28,38],product:[46,38],marketing:[82,38],finance:[82,58],admin:[70,78],research:[50,78],audit:[18,78]};
const colors={pmo:'#00ff41',design:'#a78bfa',dev:'#22d3ee',sales:'#ff7a59',product:'#38bdf8',marketing:'#e1306c',finance:'#fbbf24',admin:'#84cc16',research:'#60a5fa',audit:'#fb7185'};
const skin=['#d9a679','#f0c7a5','#a86f4b','#e0ad85'];
const hair=['#17202b','#4b2e20','#1f2937','#5b3a29'];
const statusIcon={WORKING:'⚙',IDLE:'·',WAITING_APPROVAL:'!',QUEUED:'…',APPROVED:'✓',DONE:'✓',REVIEWING:'⌕',ERROR:'×',OFFLINE:'○'};
let current={agents:[],jobs:[],events:[],queue:0,approvals:0,settings:null,execution:null};
const byId=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const formatDate=v=>v?new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Bangkok',hour12:false}):'—';
const formatTime=v=>v?new Date(v).toLocaleTimeString('ko-KR',{timeZone:'Asia/Bangkok',hour12:false}):'--:--';
const token=()=>sessionStorage.getItem('ug_ai_office_token')||'';
function seedParticles(){const box=byId('particles');if(!box)return;for(let i=0;i<26;i++){const p=document.createElement('i');p.className='particle';p.style.left=`${Math.random()*100}%`;p.style.top=`${50+Math.random()*55}%`;p.style.animationDuration=`${9+Math.random()*12}s`;p.style.animationDelay=`-${Math.random()*14}s`;box.appendChild(p)}}
async function api(path,options={}){const headers=new Headers(options.headers||{});if(token())headers.set('authorization',`Bearer ${token()}`);if(options.body&&!headers.has('content-type'))headers.set('content-type','application/json');const response=await fetch(`${API}${path}`,{...options,headers,cache:'no-store'});const data=await response.json().catch(()=>({ok:false,error:`HTTP_${response.status}`}));if(response.status===401&&path!=='/admin/login'){lock();throw new Error('SESSION_EXPIRED')}if(!response.ok||data.ok===false)throw new Error(data.error||`HTTP_${response.status}`);return data}
function lock(){sessionStorage.removeItem('ug_ai_office_token');sessionStorage.removeItem('ug_ai_office_expires');document.body.classList.add('locked');byId('commandInput').disabled=true;byId('dispatchBtn').disabled=true;byId('commandState').textContent='LOCKED';setTimeout(()=>byId('passcode').focus(),50)}
function unlock(){document.body.classList.remove('locked');byId('commandInput').disabled=false;byId('dispatchBtn').disabled=false;byId('commandState').textContent='READY'}
async function login(event){event.preventDefault();const passcode=byId('passcode').value.trim();if(!passcode)return;const button=byId('loginButton');button.disabled=true;byId('loginError').textContent='인증 중…';try{const data=await api('/admin/login',{method:'POST',body:JSON.stringify({passcode})});sessionStorage.setItem('ug_ai_office_token',data.token);sessionStorage.setItem('ug_ai_office_expires',data.expires_at);byId('passcode').value='';byId('loginError').textContent='';unlock();await loadState()}catch(error){byId('loginError').textContent=error.message==='INVALID_CREDENTIALS'?'접속 코드가 올바르지 않습니다.':error.message==='LOGIN_RATE_LIMITED'?'로그인 시도가 너무 많습니다. 15분 후 다시 시도하십시오.':`로그인 실패: ${error.message}`}finally{button.disabled=false}}
async function verifySession(){if(!token()){lock();return}try{await api('/admin/session');unlock();await loadState()}catch{lock()}}
async function logout(){try{if(token())await api('/admin/logout',{method:'POST'})}catch{}finally{lock()}}
function renderAgents(){const layer=byId('agentsLayer');layer.innerHTML='';current.agents.forEach((a,i)=>{const[x,y]=positions[a.id]||[50,50];const el=document.createElement('div');el.className=`agent ${a.status}`;el.style.left=`${x}%`;el.style.top=`${y}%`;el.style.setProperty('--agent-color',colors[a.id]||'#00ff41');el.style.setProperty('--skin',skin[i%skin.length]);el.style.setProperty('--hair',hair[i%hair.length]);el.innerHTML=`<div class="thought">${esc(a.current_task)}</div><div class="agent-status">${statusIcon[a.status]||'·'}</div><div class="avatar"><i class="head"></i><i class="hair"></i><i class="body"></i><i class="legs"></i></div><div class="agent-tag">${esc(a.name)}</div>`;el.addEventListener('click',()=>openAgent(a));layer.appendChild(el)})}
function eventCard(e){return `<article class="event"><div class="event-head"><strong>${esc(e.agent_id||e.event_type)}</strong><span class="badge ${esc(e.event_type)}">${esc(e.event_type)}</span></div><p>${esc(e.message)}</p><time>${formatTime(e.created_at)}</time></article>`}
function jobCard(j){return `<article class="task-card clickable" data-job="${j.id}"><div class="task-head"><strong>${esc(j.owner_agent_id||'pmo')}</strong><span class="badge ${esc(j.status)}">${esc(j.status)}</span></div><p>${esc(j.title)}</p><time>${formatTime(j.created_at)} · ${esc(j.risk_level)}</time></article>`}
function bindJobCards(){document.querySelectorAll('[data-job]').forEach(el=>el.addEventListener('click',()=>openJob(current.jobs.find(j=>j.id===el.dataset.job))))}
function empty(title,text){return `<article class="task-card"><strong>${title}</strong><p>${text}</p></article>`}
function renderPanels(){byId('activity').innerHTML=current.events.map(eventCard).join('')||empty('활동 없음','새 이벤트가 기록되면 표시됩니다.');byId('queue').innerHTML=current.jobs.filter(j=>!['COMPLETED'].includes(j.status)&&j.status!=='WAITING_APPROVAL').map(jobCard).join('')||empty('업무 없음','등록된 일반 업무가 없습니다.');byId('results').innerHTML=current.jobs.filter(j=>['COMPLETED','BLOCKED','FAILED','CANCELLED'].includes(j.status)).map(jobCard).join('')||empty('결과 없음','완료 또는 차단된 업무 결과가 여기에 표시됩니다.');byId('approval').innerHTML=current.jobs.filter(j=>j.status==='WAITING_APPROVAL').map(jobCard).join('')||empty('승인 대기 없음','위험 업무는 자동 실행하지 않고 이 탭에 보류됩니다.');bindJobCards()}
function renderHud(){byId('agentCount').textContent=current.agents.length;byId('activeCount').textContent=current.agents.filter(a=>a.status==='WORKING').length;byId('approvalCount').textContent=current.approvals;byId('queueCount').textContent=current.queue;const workday=Boolean(current.settings?.workday_enabled);const btn=byId('workdayBtn');btn.classList.toggle('on',workday);btn.classList.toggle('off',!workday);btn.textContent=workday?'● 24H SCHEDULER ACTIVE':'○ SCHEDULER PAUSED';const exec=current.execution||{};byId('modelText').textContent=exec.model_enabled?`MODEL: ${exec.model_provider} / ${exec.model_name||'UNSET'}`:`MODEL: BLOCKED / ${exec.disabled_reason||'KEY NOT CONFIGURED'}`;byId('executionNote').textContent=exec.model_enabled?'모델 실행이 활성화됐습니다. 외부 쓰기는 별도 승인 전까지 차단됩니다.':'관리자 기능은 활성화됐으며 AI 모델 실행은 자격증명 설정 전까지 BLOCKED로 기록됩니다.'}
function render(){renderAgents();renderPanels();renderHud()}
async function loadState(){try{const data=await api('/state');current=data;byId('runtimeText').textContent=`${data.runtime} · ${data.scheduler}`;render()}catch(error){if(error.message!=='SESSION_EXPIRED')byId('runtimeText').textContent=`API 오류 · ${error.message}`}}
async function dispatch(){const input=byId('commandInput');const command=input.value.trim();if(!command)return;const button=byId('dispatchBtn');button.disabled=true;byId('commandState').textContent='DISPATCHING';try{const data=await api('/command',{method:'POST',body:JSON.stringify({command})});input.value='';byId('commandState').textContent=`${data.job.status} → ${data.job.owner_agent_id}`;await loadState()}catch(error){byId('commandState').textContent=`ERROR: ${error.message}`}finally{button.disabled=false}}
async function toggleWorkday(){const enabled=!Boolean(current.settings?.workday_enabled);try{await api('/admin/workday',{method:'POST',body:JSON.stringify({enabled})});await loadState()}catch(error){alert(`스케줄러 변경 실패: ${error.message}`)}}
function openAgent(a){byId('modalAvatar').textContent=a.emoji;byId('modalName').textContent=a.name;byId('modalRole').textContent=a.role;byId('modalStatus').textContent=a.status;byId('modalTask').textContent=a.current_task;byId('modalUpdated').textContent=formatTime(a.updated_at);byId('agentModal').hidden=false}
function openJob(job){if(!job)return;byId('jobTitle').textContent=job.title;byId('jobStatus').textContent=job.status;byId('jobOwner').textContent=job.owner_agent_id||'pmo';byId('jobRisk').textContent=job.risk_level;byId('jobCreated').textContent=formatDate(job.created_at);const output=job.result?.output_text||job.result?.reason||job.error_message||JSON.stringify(job.result||{},null,2)||'아직 결과가 없습니다.';byId('jobResult').textContent=output;const actions=[];if(job.status==='WAITING_APPROVAL'){actions.push('<button class="reject" data-action="reject">거부</button><button class="approve" data-action="approve">승인</button>')}else if(['BLOCKED','FAILED','CANCELLED'].includes(job.status)){actions.push('<button class="retry" data-action="retry">재시도</button>')}else if(['QUEUED','APPROVED'].includes(job.status)){actions.push('<button class="reject" data-action="reject">취소</button>')}byId('jobActions').innerHTML=actions.join('');byId('jobActions').querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>jobAction(btn.dataset.action,job.id)));byId('jobModal').hidden=false}
async function jobAction(action,jobId){try{await api(`/${action}`,{method:'POST',body:JSON.stringify({job_id:jobId})});byId('jobModal').hidden=true;await loadState()}catch(error){alert(`업무 처리 실패: ${error.message}`)}}
byId('loginForm').addEventListener('submit',login);byId('logoutBtn').addEventListener('click',logout);byId('refreshBtn').addEventListener('click',loadState);byId('workdayBtn').addEventListener('click',toggleWorkday);byId('dispatchBtn').addEventListener('click',dispatch);byId('commandInput').addEventListener('keydown',e=>{if(e.key==='Enter')dispatch()});document.querySelectorAll('[data-close]').forEach(btn=>btn.addEventListener('click',()=>byId(btn.dataset.close).hidden=true));document.querySelectorAll('.modal').forEach(modal=>modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true}));document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');byId(btn.dataset.tab).classList.add('active')}));setInterval(()=>byId('clock').textContent=new Date().toLocaleString('ko-KR',{timeZone:'Asia/Bangkok',hour12:false}),1000);seedParticles();verifySession();setInterval(()=>{if(!document.body.classList.contains('locked'))loadState()},15000);