const API='https://ckzwmimmwdnmpohgvcka.supabase.co/functions/v1/unity-ai-office-dev-open';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const I18N={
 ko:{'header.subtitle':'MODERN OFFICE CONTROL CENTER','status.online':'온라인','status.scheduler':'스케줄러','status.model':'모델','actions.refresh':'새로고침','office.eyebrow':'LIVE OPERATIONS FLOOR','office.title':'AI 에이전트 오피스','office.windowCopy':'Bangkok Operations · AI Office','office.meetingZone':'PROJECT OVERVIEW','metrics.agents':'에이전트','metrics.active':'작업중','metrics.queue':'대기','metrics.approval':'승인','command.label':'COMMAND CENTER','command.placeholder':'업무 내용을 입력하십시오','command.submit':'업무 등록','tabs.jobs':'업무','tabs.results':'결과','tabs.approval':'승인','tabs.system':'시스템','side.queueSummary':'QUEUE SUMMARY','side.queueMessage':'등록된 업무 상태를 실시간으로 표시합니다.','nav.dashboard':'대시보드','nav.projects':'프로젝트','nav.agents':'에이전트','nav.analytics':'분석','nav.knowledge':'지식','nav.settings':'설정','empty.jobs':'등록된 일반 업무가 없습니다.','empty.results':'완료 또는 차단된 결과가 없습니다.','empty.approval':'승인 대기 업무가 없습니다.','feedback.required':'업무 내용을 입력하십시오.','feedback.submitting':'업무 등록 중…','feedback.done':'업무가 등록되었습니다.','feedback.failed':'업무 등록 실패','system.model':'모델 실행','system.scheduler':'24시간 스케줄러'},
 th:{'header.subtitle':'ศูนย์ควบคุมสำนักงานสมัยใหม่','status.online':'ออนไลน์','status.scheduler':'ตัวกำหนดเวลา','status.model':'โมเดล','actions.refresh':'รีเฟรช','office.eyebrow':'พื้นที่ปฏิบัติการสด','office.title':'สำนักงาน AI Agent','office.windowCopy':'Bangkok Operations · AI Office','office.meetingZone':'ภาพรวมโครงการ','metrics.agents':'เอเจนต์','metrics.active':'กำลังทำงาน','metrics.queue':'คิว','metrics.approval':'อนุมัติ','command.label':'ศูนย์คำสั่ง','command.placeholder':'กรอกรายละเอียดงาน','command.submit':'ลงทะเบียนงาน','tabs.jobs':'งาน','tabs.results':'ผลลัพธ์','tabs.approval':'อนุมัติ','tabs.system':'ระบบ','side.queueSummary':'สรุปคิว','side.queueMessage':'แสดงสถานะงานแบบเรียลไทม์','nav.dashboard':'แดชบอร์ด','nav.projects':'โครงการ','nav.agents':'เอเจนต์','nav.analytics':'วิเคราะห์','nav.knowledge':'ความรู้','nav.settings':'ตั้งค่า','empty.jobs':'ไม่มีงานทั่วไปที่ลงทะเบียน','empty.results':'ยังไม่มีผลลัพธ์ที่เสร็จหรือถูกบล็อก','empty.approval':'ไม่มีงานรออนุมัติ','feedback.required':'กรุณากรอกรายละเอียดงาน','feedback.submitting':'กำลังลงทะเบียนงาน…','feedback.done':'ลงทะเบียนงานแล้ว','feedback.failed':'ลงทะเบียนงานไม่สำเร็จ','system.model':'การทำงานของโมเดล','system.scheduler':'ตัวกำหนดเวลา 24 ชั่วโมง'}
};
const POS={sales:[16,36],product:[36,34],design:[64,34],marketing:[84,36],finance:[16,69],dev:[84,57],research:[76,79],admin:[27,84],audit:[50,82],pmo:[50,55]};
const COLOR={sales:'#e6a35b',product:'#65a8ff',design:'#d28dc8',marketing:'#ee7d83',dev:'#67c7d9',finance:'#77b98b',research:'#9a8ee8',admin:'#d2a06c',audit:'#b7a279',pmo:'#68d391'};
const HAIR={sales:'#24313b',product:'#2d2522',design:'#5f344f',marketing:'#342822',dev:'#1d252d',finance:'#283b31',research:'#30274e',admin:'#24282d',audit:'#6d5847',pmo:'#242a31'};
const SKIN=['#e6b68f','#f0c6a4','#d9a07c','#edbf9d'];
let lang=localStorage.getItem('ug_ai_locale')||'ko',data={agents:[],jobs:[],capabilities:[],contexts:[],queue:0,approvals:0},selected=null;
const t=k=>I18N[lang]?.[k]||I18N.ko[k]||k;
const time=v=>v?new Date(v).toLocaleString(lang==='th'?'th-TH':'ko-KR',{timeZone:'Asia/Bangkok',hour12:false}):'—';
async function api(path,opt={}){const h=new Headers(opt.headers||{});if(opt.body)h.set('content-type','application/json');const r=await fetch(API+path,{...opt,headers:h,cache:'no-store'}),j=await r.json().catch(()=>({error:'HTTP_'+r.status}));if(!r.ok||j.ok===false)throw Error(j.error||'HTTP_'+r.status);return j}
function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(e=>e.placeholder=t(e.dataset.i18nPlaceholder));$('languageBtn').textContent=lang==='ko'?'KO / TH':'TH / KO';render()}
function role(a){return ({pmo:'PMO',sales:'Sales',product:'Product',design:'Design',marketing:'Marketing',dev:'Dev',finance:'Finance',research:'Research',admin:'Admin',audit:'Audit'})[a.id]||a.name||a.id}
function current(id){return data.jobs.find(j=>j.owner_agent_id===id&&['QUEUED','APPROVED','RUNNING','WORKING','WAITING_APPROVAL'].includes(j.status))}
function status(a){return current(a.id)?.status||a.status||'IDLE'}
function renderAgents(){const root=$('agentsLayer');root.innerHTML='';data.agents.forEach((a,i)=>{const [x,y]=POS[a.id]||[50,50],s=status(a),busy=['QUEUED','APPROVED','RUNNING','WORKING'].includes(s),b=document.createElement('button');b.className=`agent-station${busy?' busy':''}${s==='WAITING_APPROVAL'?' approval':''}`;b.style.cssText=`left:${x}%;top:${y}%;--accent:${COLOR[a.id]||'#68d391'};--hair:${HAIR[a.id]||'#25313a'};--skin:${SKIN[i%4]};--suit:${a.id==='pmo'?'#1f3741':'#2b3945'};--state-color:${s==='WAITING_APPROVAL'?'#d79c32':busy?'#1f9d61':'#73828f'}`;b.innerHTML=`<div class="desk"><div class="agent-avatar"><i class="head"></i><i class="hair"></i><i class="body"></i><i class="shirt"></i><i class="tie"></i><i class="legs"></i><i class="badge"></i></div></div><div class="station-label"><strong>${esc(role(a))}</strong><span>${esc(s)}</span></div>`;b.onclick=()=>toast(role(a),current(a.id)?.title||a.current_task||'IDLE');root.appendChild(b)})}
function card(j){const cap=data.capabilities.find(c=>c.capability_key===j.capability_key)?.name||j.capability_key||'PMO Core';return `<article class="card clickable" data-job="${esc(j.id)}"><span class="status-badge ${esc(j.status)}">${esc(j.status)}</span><h4>${esc(j.title)}</h4><p>${esc(j.owner_agent_id||'pmo')} · ${esc(cap)}</p><small>${time(j.created_at)} · ${esc(j.risk_level||'L1')}</small></article>`}
const empty=m=>`<article class="card"><h4>—</h4><p>${esc(m)}</p></article>`;
function renderPanels(){const open=data.jobs.filter(j=>!['COMPLETED','BLOCKED','FAILED','CANCELLED','WAITING_APPROVAL'].includes(j.status)),done=data.jobs.filter(j=>['COMPLETED','BLOCKED','FAILED','CANCELLED'].includes(j.status)),approval=data.jobs.filter(j=>j.status==='WAITING_APPROVAL'),ex=data.execution||{};$('jobs').innerHTML=open.map(card).join('')||empty(t('empty.jobs'));$('results').innerHTML=done.map(card).join('')||empty(t('empty.results'));$('approval').innerHTML=approval.map(card).join('')||empty(t('empty.approval'));$('system').innerHTML=`<article class="card"><span class="status-badge ${ex.model_enabled?'COMPLETED':'BLOCKED'}">${ex.model_enabled?'ENABLED':'BLOCKED'}</span><h4>${t('system.model')}</h4><p>${esc(ex.model_provider||'NONE')} · ${esc(ex.model_name||'UNSET')}</p><small>${esc(ex.disabled_reason||'OPENAI_API_KEY_NOT_CONFIGURED')}</small></article><article class="card"><h4>${t('system.scheduler')}</h4><p>${data.settings?.workday_enabled?'ACTIVE':'PAUSED'}</p><small>Capability ${data.capabilities.length} · Context ${data.contexts.length}</small></article>`;document.querySelectorAll('[data-job]').forEach(e=>e.onclick=()=>openJob(e.dataset.job))}
function renderMetric(){const active=data.agents.filter(a=>['QUEUED','APPROVED','RUNNING','WORKING'].includes(status(a))).length;[['agentCount',data.agents.length],['activeCount',active],['queueCount',data.queue||0],['approvalCount',data.approvals||0],['officeActive',active],['officeQueue',data.queue||0],['officeApproval',data.approvals||0],['queueSummary',data.queue||0]].forEach(([id,v])=>$(id).textContent=v);$('schedulerState').textContent=data.settings?.workday_enabled?'ACTIVE':'PAUSED';$('modelState').textContent=data.execution?.model_enabled?String(data.execution.model_name||'ENABLED').toUpperCase():'BLOCKED'}
function render(){renderAgents();renderPanels();renderMetric()}
async function load(silent=false){try{data=await api('/state');$('connectionState').textContent='API';$('runtimeText').textContent=`${data.mode||data.access_mode||'DEV OPEN'} · Capability ${data.capabilities?.length||0} · Context ${data.contexts?.length||0}`.replaceAll('_',' ');render()}catch(e){$('connectionState').textContent='OFFLINE';$('runtimeText').textContent='API ERROR · '+e.message;if(!silent)toast('API ERROR',e.message,true)}}
function toast(title,msg,err=false){const n=document.createElement('div');n.className='toast'+(err?' error':'');n.innerHTML=`<b>${esc(title)}</b><span>${esc(msg)}</span>`;$('toastArea').appendChild(n);setTimeout(()=>n.remove(),4000)}
function panel(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===name))}
async function dispatch(){const command=$('commandInput').value.trim();if(!command){$('feedback').className='feedback err';$('feedback').textContent=t('feedback.required');return}const b=$('dispatchBtn');b.disabled=true;$('commandState').textContent='SUBMITTING';$('feedback').textContent=t('feedback.submitting');try{const r=await api('/command',{method:'POST',body:JSON.stringify({command})});$('commandInput').value='';$('commandState').textContent=r.job?.status||'QUEUED';$('feedback').className='feedback ok';$('feedback').textContent=t('feedback.done');toast(t('feedback.done'),`${r.job?.owner_agent_id||'pmo'} · ${r.job?.status||'QUEUED'}`);await load(true);panel(r.job?.status==='WAITING_APPROVAL'?'approval':'jobs')}catch(e){$('commandState').textContent='ERROR';$('feedback').className='feedback err';$('feedback').textContent=t('feedback.failed')+' · '+e.message;toast(t('feedback.failed'),e.message,true)}finally{b.disabled=false}}
function openJob(id){selected=data.jobs.find(j=>String(j.id)===String(id));if(!selected)return;$('modalTitle').textContent=selected.title;$('modalStatus').textContent=selected.status;$('modalOwner').textContent=selected.owner_agent_id||'pmo';$('modalRisk').textContent=selected.risk_level||'L1';$('modalResult').textContent=selected.result?.output_text||selected.result?.reason||selected.error_message||JSON.stringify(selected.result||{},null,2)||'—';const a=[];if(selected.status==='WAITING_APPROVAL')a.push('approve','reject');if(['BLOCKED','FAILED','CANCELLED'].includes(selected.status))a.push('retry');$('modalActions').innerHTML=a.map(x=>`<button data-act="${x}">${x.toUpperCase()}</button>`).join('');document.querySelectorAll('[data-act]').forEach(x=>x.onclick=()=>act(x.dataset.act));$('jobModal').hidden=false}
async function act(name){try{await api('/'+name,{method:'POST',body:JSON.stringify({job_id:selected.id})});$('jobModal').hidden=true;toast('JOB UPDATED',name.toUpperCase());await load(true)}catch(e){toast('JOB ERROR',e.message,true)}}
$('dispatchBtn').onclick=dispatch;$('commandInput').onkeydown=e=>{if(e.key==='Enter')dispatch()};$('refreshBtn').onclick=()=>load();$('languageBtn').onclick=()=>{lang=lang==='ko'?'th':'ko';localStorage.setItem('ug_ai_locale',lang);translate()};$('modalClose').onclick=()=>{$('jobModal').hidden=true};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>panel(b.dataset.panel));setInterval(()=>{$('clock').textContent=new Date().toLocaleString(lang==='th'?'th-TH':'ko-KR',{timeZone:'Asia/Bangkok',hour12:false})},1000);translate();load();setInterval(()=>load(true),15000);
