document.querySelector('.office-map-image').src='data:image/webp;base64,'+(window.__UG_OFFICE_IMAGE||'');
const API='https://ckzwmimmwdnmpohgvcka.supabase.co/functions/v1/unity-ai-office-dev-open-v2';
const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const translations={ko:{'status.title':'OFFICE STATUS','status.agents':'AGENTS','status.active':'ACTIVE','status.queue':'QUEUE','status.approval':'APPROVAL','tabs.jobs':'JOBS','tabs.results':'RESULTS','tabs.approval':'APPROVAL','tabs.system':'SYSTEM','queue.title':'QUEUE','approval.title':'APPROVAL','command.title':'COMMAND CENTER','command.placeholder':'지시를 입력하세요...','command.execute':'실행','nav.dashboard':'DASHBOARD','nav.projects':'PROJECTS','nav.agents':'AGENTS','nav.analytics':'ANALYTICS','nav.knowledge':'KNOWLEDGE','nav.resources':'RESOURCES','nav.reports':'REPORTS','nav.settings':'SETTINGS','health.title':'SYSTEM HEALTH','empty.jobs':'표시할 업무가 없습니다.','empty.queue':'대기 업무 없음','empty.approval':'승인 대기 없음','empty.results':'완료 또는 차단된 결과가 없습니다.','action.approve':'승인','action.reject':'거부','action.retry':'재시도','action.pause':'스케줄러 중지','action.activate':'스케줄러 활성화','action.refresh':'새로고침','message.updated':'상태가 업데이트되었습니다.','message.command':'업무가 등록되었습니다.','message.error':'처리 실패'},th:{'status.title':'สถานะสำนักงาน','status.agents':'เอเจนต์','status.active':'กำลังทำงาน','status.queue':'คิวงาน','status.approval':'รออนุมัติ','tabs.jobs':'งาน','tabs.results':'ผลลัพธ์','tabs.approval':'อนุมัติ','tabs.system':'ระบบ','queue.title':'คิวงาน','approval.title':'รออนุมัติ','command.title':'ศูนย์สั่งการ','command.placeholder':'ป้อนคำสั่ง...','command.execute':'ดำเนินการ','nav.dashboard':'แดชบอร์ด','nav.projects':'โครงการ','nav.agents':'เอเจนต์','nav.analytics':'วิเคราะห์','nav.knowledge':'ความรู้','nav.resources':'ทรัพยากร','nav.reports':'รายงาน','nav.settings':'ตั้งค่า','health.title':'สุขภาพระบบ','empty.jobs':'ไม่มีงานที่จะแสดง','empty.queue':'ไม่มีงานในคิว','empty.approval':'ไม่มีงานรออนุมัติ','empty.results':'ยังไม่มีผลลัพธ์ที่เสร็จหรือถูกบล็อก','action.approve':'อนุมัติ','action.reject':'ปฏิเสธ','action.retry':'ลองใหม่','action.pause':'หยุดตัวกำหนดเวลา','action.activate':'เปิดตัวกำหนดเวลา','action.refresh':'รีเฟรช','message.updated':'อัปเดตสถานะแล้ว','message.command':'ลงทะเบียนงานแล้ว','message.error':'ดำเนินการไม่สำเร็จ'}};
let locale='ko';try{locale=localStorage.getItem('ug_ai_locale')||'ko'}catch{}
let state={agents:[],jobs:[],events:[],contexts:[],capabilities:[],templates:[],tool_policies:[],queue:0,approvals:0,settings:{},execution:{},usage_summary:{}};let selectedTab='jobs',selectedJobId=null,loading=false;
const departmentPositions={sales:[15,13],product:[42,13],design:[72,13],marketing:[15,36],pmo:[49,48],dev:[79,36],finance:[15,61],research:[78,61],admin:[15,82],system:[40,82],pmo_support:[72,82]},departmentAliases={pmo_support:'admin',system:'dev'};
const t=key=>translations[locale]?.[key]||translations.ko[key]||key,activeStatuses=['QUEUED','RUNNING','WORKING','APPROVED'],resultStatuses=['COMPLETED','BLOCKED','FAILED','CANCELLED'];
function applyI18n(){document.documentElement.lang=locale==='th'?'th':'ko';document.body.style.fontFamily=locale==='th'?'var(--ug-font-body-th)':'var(--ug-font-body-ko)';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));$('languageButton').textContent=locale.toUpperCase()}
function activeJobs(){return state.jobs.filter(job=>activeStatuses.includes(job.status))}function approvalJobs(){return state.jobs.filter(job=>job.status==='WAITING_APPROVAL')}function resultJobs(){return state.jobs.filter(job=>resultStatuses.includes(job.status))}function currentJobFor(agentId){return state.jobs.find(job=>job.owner_agent_id===agentId&&(activeStatuses.includes(job.status)||job.status==='WAITING_APPROVAL'))}function statusClass(status=''){return String(status).toLowerCase()}function formatDate(value){return value?new Date(value).toLocaleString(locale==='th'?'th-TH':'ko-KR',{timeZone:'Asia/Bangkok',hour12:false}):'—'}function shortId(id){return String(id||'').slice(0,8)}function capabilityName(key){return state.capabilities.find(c=>c.capability_key===key)?.name||key||'—'}function outputText(job){const result=job?.result||{};return result.output_text||result.reason||job?.error_message||result.message||job?.payload?.description||job?.title||'—'}
async function api(path,options={}){const headers=new Headers(options.headers||{});if(options.body&&!headers.has('content-type'))headers.set('content-type','application/json');const response=await fetch(`${API}${path}`,{...options,headers,cache:'no-store'});const data=await response.json().catch(()=>({ok:false,error:`HTTP_${response.status}`}));if(!response.ok||data.ok===false)throw new Error(data.error||`HTTP_${response.status}`);return data}
function updateHeader(){const created=new Date('2026-07-30T00:00:00+07:00'),days=Math.max(1,Math.ceil((Date.now()-created.getTime())/86400000));$('dayCount').textContent=`DAY ${days}`;const usage=state.usage_summary?.daily||{};$('costValue').textContent=Number(usage.estimated_cost_thb||0).toLocaleString(locale==='th'?'th-TH':'ko-KR',{maximumFractionDigits:2});$('approvalResource').textContent=state.approvals||approvalJobs().length;const workday=Boolean(state.settings?.workday_enabled);$('energyValue').textContent=workday?'120/120':'0/120';$('onlineText').textContent=state.ok===false?'OFFLINE':'ONLINE'}
function updateClock(){$('clockText').textContent=new Date().toLocaleTimeString(locale==='th'?'th-TH':'ko-KR',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hour12:false})}
function renderDepartmentLayer(){const layer=$('departmentLayer');layer.innerHTML='';Object.entries(departmentPositions).forEach(([id,[x,y]])=>{const agentId=departmentAliases[id]||id,agent=state.agents.find(item=>item.id===agentId),job=currentJobFor(agentId),status=job?.status||agent?.status||'IDLE',button=document.createElement('button');button.type='button';button.className=`department-hotspot ${statusClass(status)} ${activeStatuses.includes(status)?'active':''}`;button.style.left=`${x}%`;button.style.top=`${y}%`;button.setAttribute('aria-label',`${id.toUpperCase()} · ${status}`);button.title=`${id.toUpperCase()} · ${status}${job?` · ${job.title}`:''}`;button.addEventListener('click',()=>openAgentDialog(id,agent,job));layer.appendChild(button)})}
function showDialog(title,html){$('dialogTitle').textContent=title;$('dialogContent').innerHTML=html;$('sectionDialog').showModal()}
function actionButtons(job){const actions=[];if(job?.status==='WAITING_APPROVAL')actions.push(['approve',t('action.approve'),'approve'],['reject',t('action.reject'),'reject']);if(['BLOCKED','FAILED','CANCELLED'].includes(job?.status))actions.push(['retry',t('action.retry'),'retry']);if(!actions.length)return '';return `<div class="job-actions">${actions.map(([action,label,cls])=>`<button type="button" class="action-button ${cls}" data-job-action="${action}" data-job-id="${escapeHtml(job.id)}">${escapeHtml(label)}</button>`).join('')}</div>`}
function bindActionButtons(root=document){root.querySelectorAll('[data-job-action]').forEach(button=>button.addEventListener('click',()=>actOnJob(button.dataset.jobAction,button.dataset.jobId)))}
function openAgentDialog(roomId,agent,job){const html=`<div class="dialog-grid"><div class="dialog-stat"><span>STATUS</span><strong>${escapeHtml(job?.status||agent?.status||'IDLE')}</strong></div><div class="dialog-stat"><span>ROLE</span><strong>${escapeHtml(agent?.role||roomId)}</strong></div><div class="dialog-stat"><span>CAPABILITY</span><strong>${escapeHtml(capabilityName(job?.capability_key))}</strong></div></div><div class="dialog-list" style="margin-top:14px"><article class="dialog-row"><strong>CURRENT TASK</strong><small>${escapeHtml(job?.title||agent?.current_task||'IDLE')}</small></article><article class="dialog-row"><strong>UPDATED</strong><small>${escapeHtml(formatDate(job?.updated_at||agent?.updated_at))}</small></article></div>${actionButtons(job)}`;showDialog(roomId.replace('_',' ').toUpperCase(),html);bindActionButtons($('dialogContent'))}
