const BASE = Deno.env.get('SUPABASE_URL') || '';
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || '';
const OPENAI_KEY = Deno.env.get('OPENAI_API_KEY') || '';
const ANTHROPIC_KEY = Deno.env.get('ANTHROPIC_API_KEY') || '';
const UPSTREAM = `${BASE}/functions/v1/unity-ai-office-dev-open`;
const REST = `${BASE}/rest/v1`;
const STAGE = 'ONLINE_MULTI_AGENT_STAGE_7_REFERENCE_V2';
const CORS = {
  'access-control-allow-origin':'*',
  'access-control-allow-headers':'content-type, authorization, apikey, x-client-info',
  'access-control-allow-methods':'GET, POST, OPTIONS'
};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...CORS,'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function routePath(req){const marker='/unity-ai-office-dev-open-v2';const path=new URL(req.url).pathname;const index=path.indexOf(marker);return index>=0?path.slice(index+marker.length)||'/':'/'}
async function rest(path){const response=await fetch(`${REST}/${path}`,{headers:{apikey:SERVICE_KEY,authorization:`Bearer ${SERVICE_KEY}`,'content-type':'application/json'}});if(!response.ok)throw new Error(`REST_${response.status}`);return await response.json()}
function bangkokParts(value){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(value));const map=Object.fromEntries(parts.map(part=>[part.type,part.value]));return{day:`${map.year}-${map.month}-${map.day}`,month:`${map.year}-${map.month}`}}
function usageSummary(rows){const current=bangkokParts(new Date()),daily={total_tokens:0,estimated_cost_thb:0},monthly={total_tokens:0,estimated_cost_thb:0};for(const row of rows){const created=bangkokParts(String(row.created_at||'')),tokens=Number(row.total_tokens||0),cost=Number(row.estimated_cost_thb||0);if(created.month===current.month){monthly.total_tokens+=tokens;monthly.estimated_cost_thb+=cost}if(created.day===current.day){daily.total_tokens+=tokens;daily.estimated_cost_thb+=cost}}daily.estimated_cost_thb=Number(daily.estimated_cost_thb.toFixed(4));monthly.estimated_cost_thb=Number(monthly.estimated_cost_thb.toFixed(4));return{daily,monthly}}
async function enhancedState(){const[upstreamResponse,usage,prices,toolLedger]=await Promise.all([fetch(`${UPSTREAM}/state`,{headers:{'cache-control':'no-store'}}),rest('ai_office_usage_ledger?select=total_tokens,estimated_cost_thb,created_at&order=created_at.desc&limit=5000'),rest('ai_office_model_pricing?select=pricing_key,provider,model,active,verified_at,input_cost_per_million_thb,output_cost_per_million_thb&active=eq.true&order=verified_at.desc'),rest('ai_office_tool_ledger?select=status,external_effect,created_at&order=created_at.desc&limit=500')]);const state=await upstreamResponse.json();if(!upstreamResponse.ok||state?.ok===false)return json(state,upstreamResponse.status);const usageRows=Array.isArray(usage)?usage:[],priceRows=Array.isArray(prices)?prices:[],toolRows=Array.isArray(toolLedger)?toolLedger:[];state.gateway_mode=STAGE;state.credential_status={...(state.credential_status||{}),openai_configured:Boolean(OPENAI_KEY),anthropic_configured:Boolean(ANTHROPIC_KEY)};state.usage_summary=usageSummary(usageRows);state.verified_model_prices=priceRows;state.tool_ledger_summary={total:toolRows.length,external_effect_attempts:toolRows.filter(row=>Boolean(row.external_effect)).length,succeeded:toolRows.filter(row=>String(row.status).toUpperCase()==='COMPLETED').length,blocked_or_denied:toolRows.filter(row=>['BLOCKED','DENIED','REJECTED'].includes(String(row.status).toUpperCase())).length};state.generatedAt=new Date().toISOString();return json(state)}
async function proxy(req,path){const body=['GET','HEAD'].includes(req.method)?undefined:await req.text();const response=await fetch(`${UPSTREAM}${path}`,{method:req.method,headers:{'content-type':req.headers.get('content-type')||'application/json'},body});const text=await response.text();return new Response(text,{status:response.status,headers:{...CORS,'content-type':response.headers.get('content-type')||'application/json; charset=utf-8','cache-control':'no-store'}})}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});try{const path=routePath(req);if(path==='/state'&&req.method==='GET')return await enhancedState();if(path==='/health'&&req.method==='GET')return json({ok:true,service:'unity-ai-office-dev-open-v2',stage:STAGE,auth:'disabled-during-initial-development',openai_configured:Boolean(OPENAI_KEY),anthropic_configured:Boolean(ANTHROPIC_KEY),time:new Date().toISOString()});return await proxy(req,path)}catch(error){console.error(error);return json({ok:false,error:'V2_GATEWAY_INTERNAL_ERROR'},500)}});