(() => {
  'use strict';

  const API = 'https://ckzwmimmwdnmpohgvcka.supabase.co/functions/v1/unity-ai-office-dev-open-v2';
  const ACTIVE = new Set(['QUEUED', 'APPROVED', 'RUNNING', 'WORKING']);
  const RESULTS = new Set(['COMPLETED', 'BLOCKED', 'FAILED', 'CANCELLED']);
  const TILE = 48;
  const COLS = 28;
  const ROWS = 17;
  const WORLD_W = COLS * TILE;
  const WORLD_H = ROWS * TILE;

  const $ = id => document.getElementById(id);
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const shortTime = value => value ? new Date(value).toLocaleTimeString('ko-KR', {timeZone:'Asia/Bangkok', hour:'2-digit', minute:'2-digit', hour12:false}) : '—';

  const ui = {
    connection: $('connectionLabel'), live: document.querySelector('.live'), clock: $('bangkokClock'),
    agents: $('agentCount'), active: $('activeCount'), queue: $('queueCount'), approval: $('approvalCount'),
    jobsBadge: $('jobsBadge'), approvalBadge: $('approvalBadge'), jobsList: $('jobsList'), approvalList: $('approvalList'), eventsList: $('eventsList'),
    runtime: $('runtimeLabel'), sync: $('lastSync'), feedback: $('commandFeedback'), command: $('commandInput'), commandButton: $('commandButton'),
    selectedPortrait: $('selectedPortrait'), selectedName: $('selectedName'), selectedRole: $('selectedRole'), selectedStatus: $('selectedStatus'),
    selectedState: $('selectedState'), selectedLocation: $('selectedLocation'), selectedEnergy: $('selectedEnergy'), selectedEnergyValue: $('selectedEnergyValue'), selectedTask: $('selectedTask'),
    dialog: $('jobDialog'), dialogStatus: $('dialogStatus'), dialogTitle: $('dialogTitle'), dialogMeta: $('dialogMeta'), dialogBody: $('dialogBody'), dialogActions: $('dialogActions'),
    loading: $('gameLoading'), error: $('gameError'), speech: $('npcSpeech')
  };

  const ROLE_CONFIG = {
    pmo:{name:'PMO',role:'Command & Coordination',shirt:'#d1a65f',hair:'#3a241a',skin:'#e5b58e',desk:[13,7]},
    design:{name:'DESIGN',role:'UX & System Design',shirt:'#a58ae8',hair:'#332443',skin:'#f0c09a',desk:[18,3]},
    dev:{name:'DEV',role:'Engineering',shirt:'#4ebbd1',hair:'#18212a',skin:'#d39a73',desk:[21,6]},
    sales:{name:'SALES',role:'Sales Operations',shirt:'#e17858',hair:'#573021',skin:'#efbd91',desk:[4,3]},
    product:{name:'PRODUCT',role:'Product & Quality',shirt:'#5da7dc',hair:'#5a3a24',skin:'#e7b589',desk:[9,3]},
    marketing:{name:'MARKETING',role:'Growth & Content',shirt:'#d65f88',hair:'#2b202a',skin:'#dca37f',desk:[4,8]},
    finance:{name:'FINANCE',role:'Finance Control',shirt:'#d3ad55',hair:'#2b2420',skin:'#f1c3a0',desk:[4,13]},
    admin:{name:'ADMIN',role:'Administration',shirt:'#88b85a',hair:'#442e23',skin:'#e4ad83',desk:[10,13]},
    research:{name:'RESEARCH',role:'Market Intelligence',shirt:'#648ed6',hair:'#1d2b3b',skin:'#dca278',desk:[20,13]},
    audit:{name:'AUDIT',role:'Verification & Risk',shirt:'#cc6e73',hair:'#382324',skin:'#edb793',desk:[24,13]}
  };

  const STATIONS = {
    coffee:{tile:[13,14],label:'COFFEE BAR',icon:'☕'},meetingA:{tile:[13,4],label:'STRATEGY ROOM',icon:'◆'},meetingB:{tile:[15,4],label:'STRATEGY ROOM',icon:'◆'},
    printer:{tile:[15,13],label:'DOCUMENT HUB',icon:'▤'},loungeA:{tile:[24,8],label:'LOUNGE',icon:'…'},loungeB:{tile:[22,8],label:'LOUNGE',icon:'…'},
    board:{tile:[13,2],label:'PLANNING BOARD',icon:'▥'},server:{tile:[25,4],label:'SERVER ROOM',icon:'⚠'},lobby:{tile:[13,15],label:'LOBBY',icon:'◇'}
  };

  let appState = {agents:[],jobs:[],events:[],queue:0,approvals:0,settings:{},execution:{}};
  let gameScene = null;
  let selectedNpcId = null;
  let pollTimer = null;

  function setConnection(ok,label){ui.connection.textContent=label;ui.live.classList.toggle('online',ok);ui.live.classList.toggle('offline',!ok)}
  async function api(path,options={}){const headers=new Headers(options.headers||{});if(options.body)headers.set('content-type','application/json');const response=await fetch(API+path,{...options,headers,cache:'no-store'});const data=await response.json().catch(()=>({ok:false,error:`HTTP_${response.status}`}));if(!response.ok||data.ok===false)throw new Error(data.error||`HTTP_${response.status}`);return data}
  function currentJobFor(agentId){return appState.jobs.find(job=>job.owner_agent_id===agentId&&(ACTIVE.has(job.status)||job.status==='WAITING_APPROVAL'))||null}
  function jobOutput(job){return job?.result?.output_text||job?.result?.reason||job?.error_message||job?.payload?.description||'아직 처리 결과가 없습니다.'}
  function jobCard(job){return `<article class="list-card" data-job-id="${escapeHtml(job.id)}"><span class="badge ${escapeHtml(job.status)}">${escapeHtml(job.status)}</span><strong>${escapeHtml(job.title)}</strong><p>${escapeHtml(job.owner_agent_id||'pmo')} · ${escapeHtml(job.capability_key||'pmo_core')}</p><small>${shortTime(job.updated_at||job.created_at)}</small></article>`}
  function bindCards(root){root.querySelectorAll('[data-job-id]').forEach(card=>card.addEventListener('click',()=>openJob(card.dataset.jobId)))}
  function renderLists(){const jobs=appState.jobs.filter(job=>ACTIVE.has(job.status)),approvals=appState.jobs.filter(job=>job.status==='WAITING_APPROVAL');ui.jobsList.innerHTML=jobs.map(jobCard).join('')||'<div class="empty-card">진행 중인 업무가 없습니다.</div>';ui.approvalList.innerHTML=approvals.map(jobCard).join('')||'<div class="empty-card">승인 대기 업무가 없습니다.</div>';ui.eventsList.innerHTML=(appState.events||[]).slice(0,35).map(event=>`<article class="list-card"><span class="badge">${escapeHtml(event.event_type||'EVENT')}</span><strong>${escapeHtml(event.message||'System event')}</strong><p>${escapeHtml(event.agent_id||'system')}</p><small>${shortTime(event.created_at)}</small></article>`).join('')||'<div class="empty-card">표시할 이벤트가 없습니다.</div>';bindCards(ui.jobsList);bindCards(ui.approvalList);ui.jobsBadge.textContent=jobs.length;ui.approvalBadge.textContent=approvals.length}
  function renderHeader(){ui.agents.textContent=appState.agents.length||Object.keys(ROLE_CONFIG).length;ui.active.textContent=appState.agents.filter(agent=>currentJobFor(agent.id)).length;ui.queue.textContent=appState.queue??appState.jobs.filter(job=>ACTIVE.has(job.status)).length;ui.approval.textContent=appState.approvals??appState.jobs.filter(job=>job.status==='WAITING_APPROVAL').length;ui.runtime.textContent=appState.settings?.workday_enabled?'SCHEDULER ACTIVE':'SCHEDULER PAUSED'}
  function renderSelected(){if(!selectedNpcId||!gameScene?.npcs?.has(selectedNpcId))return;const npc=gameScene.npcs.get(selectedNpcId),sourceAgent=appState.agents.find(agent=>agent.id===selectedNpcId),job=currentJobFor(selectedNpcId),status=job?.status||sourceAgent?.status||npc.mode||'IDLE';ui.selectedPortrait.textContent=selectedNpcId.slice(0,2).toUpperCase();ui.selectedPortrait.style.borderColor=npc.config.shirt;ui.selectedPortrait.style.color=npc.config.shirt;ui.selectedName.textContent=sourceAgent?.name||npc.config.name;ui.selectedRole.textContent=sourceAgent?.role||npc.config.role;ui.selectedState.textContent=status;ui.selectedLocation.textContent=npc.locationLabel||'OFFICE';const energy=Math.round(npc.energy);ui.selectedEnergy.style.width=`${energy}%`;ui.selectedEnergyValue.textContent=`${energy}%`;ui.selectedTask.textContent=job?.title||npc.activityLabel||'자율 업무 대기';ui.selectedStatus.className='status-dot '+(status==='WAITING_APPROVAL'?'waiting':(['BLOCKED','FAILED'].includes(status)?'blocked':(ACTIVE.has(status)?'active':'')))}
  async function loadState(silent=false){try{const state=await api('/state');appState=state;setConnection(true,'API ONLINE');ui.sync.textContent=new Date().toLocaleTimeString('ko-KR',{timeZone:'Asia/Bangkok',hour12:false});renderHeader();renderLists();gameScene?.applyOperationalState(state);renderSelected()}catch(error){setConnection(false,'API OFFLINE');ui.runtime.textContent=error.message;if(!silent)setFeedback(`연결 실패: ${error.message}`,'err')}}
  function setFeedback(message,type=''){ui.feedback.className=`command-feedback ${type}`;ui.feedback.textContent=message}
  async function submitCommand(event){event.preventDefault();const command=ui.command.value.trim();if(!command)return setFeedback('업무 내용을 입력하십시오.','err');ui.commandButton.disabled=true;setFeedback('실제 작업 큐에 등록 중입니다.');try{const data=await api('/command',{method:'POST',body:JSON.stringify({command})});ui.command.value='';setFeedback(`등록 완료 · ${data.job.owner_agent_id} · ${data.job.status}`,'ok');await loadState(true);gameScene?.focusAgent(data.job.owner_agent_id,true)}catch(error){setFeedback(`등록 실패: ${error.message}`,'err')}finally{ui.commandButton.disabled=false}}
  function openJob(id){const job=appState.jobs.find(item=>item.id===id);if(!job)return;ui.dialogStatus.textContent=job.status;ui.dialogTitle.textContent=job.title;ui.dialogMeta.textContent=`${job.owner_agent_id||'pmo'} · ${job.capability_key||'pmo_core'} · ${job.risk_level||'L1'}`;ui.dialogBody.textContent=jobOutput(job);const buttons=[];if(job.status==='WAITING_APPROVAL')buttons.push(['approve','승인','approve'],['reject','거부','reject']);if(['BLOCKED','FAILED','CANCELLED'].includes(job.status))buttons.push(['retry','재시도','']);ui.dialogActions.innerHTML=buttons.map(([action,label,cls])=>`<button type="button" class="${cls}" data-action="${action}">${label}</button>`).join('');ui.dialogActions.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>actOnJob(button.dataset.action,job.id)));ui.dialog.showModal()}
  async function actOnJob(action,jobId){try{await api(`/${action}`,{method:'POST',body:JSON.stringify({job_id:jobId})});ui.dialog.close();setFeedback(`업무 상태 변경 완료 · ${action.toUpperCase()}`,'ok');await loadState(true)}catch(error){setFeedback(`상태 변경 실패: ${error.message}`,'err')}}
  function selectNpc(id,center=false){selectedNpcId=id;gameScene?.setSelected(id);if(center)gameScene?.focusAgent(id,false);renderSelected()}
  function showSpeech(npc,text,duration=2200){if(!gameScene||!npc||!text)return;const canvasBounds=gameScene.game.canvas.getBoundingClientRect(),screen=gameScene.cameras.main.worldView,zoom=gameScene.cameras.main.zoom;ui.speech.textContent=text;ui.speech.hidden=false;ui.speech.style.left=`${Math.max(8,(npc.sprite.x-screen.x)*zoom*canvasBounds.width/gameScene.scale.width-20)}px`;ui.speech.style.top=`${Math.max(55,(npc.sprite.y-42-screen.y)*zoom*canvasBounds.height/gameScene.scale.height-55)}px`;clearTimeout(showSpeech.timer);showSpeech.timer=setTimeout(()=>{ui.speech.hidden=true},duration)}
  function setupTabs(){document.querySelectorAll('.panel-tabs button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.panel-tabs button').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.tab-panel').forEach(panel=>panel.classList.toggle('active',panel.id===`${button.dataset.tab}Panel`))}))}

  function createAgentSheet(scene,id,config){const frameW=24,frameH=34,frames=4,dirs=4,canvas=document.createElement('canvas');canvas.width=frameW*frames;canvas.height=frameH*dirs;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;for(let dir=0;dir<dirs;dir++){for(let frame=0;frame<frames;frame++){const ox=frame*frameW,oy=dir*frameH,walk=[0,1,0,-1][frame],arm=[0,-1,0,1][frame];ctx.fillStyle='rgba(0,0,0,.28)';ctx.fillRect(ox+5,oy+30,14,3);ctx.fillStyle='#26313a';if(dir===0||dir===1){ctx.fillRect(ox+7+walk,oy+24,4,7);ctx.fillRect(ox+13-walk,oy+24,4,7)}else{ctx.fillRect(ox+8,oy+24+walk,4,7);ctx.fillRect(ox+13,oy+24-walk,4,7)}ctx.fillStyle=config.shirt;ctx.fillRect(ox+6,oy+13,12,13);ctx.fillStyle='#ffffff18';ctx.fillRect(ox+7,oy+14,10,2);ctx.fillStyle=config.skin;if(dir===2||dir===3){ctx.fillRect(ox+4,oy+15+arm,3,9);ctx.fillRect(ox+17,oy+15-arm,3,9)}else{ctx.fillRect(ox+4+arm,oy+15,3,9);ctx.fillRect(ox+17-arm,oy+15,3,9)}ctx.fillRect(ox+7,oy+4,10,10);ctx.fillStyle=config.hair;ctx.fillRect(ox+7,oy+2,10,5);ctx.fillRect(ox+6,oy+5,3,5);ctx.fillRect(ox+15,oy+5,3,5);if(dir!==3){ctx.fillStyle='#252a2e';if(dir===2){ctx.fillRect(ox+8,oy+8,2,1);ctx.fillRect(ox+14,oy+8,2,1)}else if(dir===0){ctx.fillRect(ox+9,oy+8,2,1);ctx.fillRect(ox+14,oy+8,2,1)}else{ctx.fillRect(ox+8,oy+8,2,1);ctx.fillRect(ox+13,oy+8,2,1)}}ctx.fillStyle='#111920';ctx.fillRect(ox+6,oy+25,12,2);ctx.fillStyle='#d7b96b';ctx.fillRect(ox+10,oy+17,4,2)}}const texture=scene.textures.addCanvas(`agent-${id}`,canvas);for(let dir=0;dir<dirs;dir++)for(let frame=0;frame<frames;frame++)texture.add(dir*4+frame,0,frame*frameW,dir*frameH,frameW,frameH);['down','left','right','up'].forEach((name,dir)=>scene.anims.create({key:`${id}-walk-${name}`,frames:[0,1,2,3].map(i=>({key:`agent-${id}`,frame:dir*4+i})),frameRate:8,repeat:-1}))}

  class AStarGrid{
    constructor(cols,rows){this.cols=cols;this.rows=rows;this.blocked=new Set()}
    key(x,y){return`${x},${y}`}
    block(x,y,w=1,h=1){for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)if(xx>=0&&yy>=0&&xx<this.cols&&yy<this.rows)this.blocked.add(this.key(xx,yy))}
    isOpen(x,y){return x>=0&&y>=0&&x<this.cols&&y<this.rows&&!this.blocked.has(this.key(x,y))}
    nearestOpen(x,y){if(this.isOpen(x,y))return[x,y];for(let r=1;r<8;r++)for(let yy=y-r;yy<=y+r;yy++)for(let xx=x-r;xx<=x+r;xx++)if(this.isOpen(xx,yy))return[xx,yy];return[1,1]}
    path(start,end){const[sx,sy]=this.nearestOpen(...start),[ex,ey]=this.nearestOpen(...end),open=[{x:sx,y:sy,g:0,f:0}],came=new Map(),g=new Map([[this.key(sx,sy),0]]),closed=new Set(),h=(x,y)=>Math.abs(ex-x)+Math.abs(ey-y);open[0].f=h(sx,sy);while(open.length){open.sort((a,b)=>a.f-b.f);const cur=open.shift(),ck=this.key(cur.x,cur.y);if(closed.has(ck))continue;if(cur.x===ex&&cur.y===ey){const out=[];let k=ck;while(k){const[x,y]=k.split(',').map(Number);out.unshift([x,y]);k=came.get(k)}return out}closed.add(ck);for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=cur.x+dx,ny=cur.y+dy,nk=this.key(nx,ny);if(!this.isOpen(nx,ny)||closed.has(nk))continue;const ng=cur.g+1;if(ng<(g.get(nk)??Infinity)){g.set(nk,ng);came.set(nk,ck);open.push({x:nx,y:ny,g:ng,f:ng+h(nx,ny)})}}}return[]}
  }

  class NPC{
    constructor(scene,id,config){this.scene=scene;this.id=id;this.config=config;this.mode='IDLE';this.energy=84+Math.random()*15;this.activityLabel='자율 업무 대기';this.locationLabel='WORKSTATION';this.path=[];this.pathIndex=0;this.nextDecision=0;this.actionUntil=0;this.operationalJob=null;this.lastStatus='';const[x,y]=scene.tileToWorld(config.desk[0],config.desk[1]);this.sprite=scene.add.sprite(x,y,`agent-${id}`,0).setOrigin(.5,.88).setScale(1.55).setDepth(y+50).setInteractive({useHandCursor:true});this.nameplate=scene.add.container(x,y-45).setDepth(y+100);const bg=scene.add.rectangle(0,0,78,15,0x081017,.88).setStrokeStyle(1,Phaser.Display.Color.HexStringToColor(config.shirt).color,.75),label=scene.add.text(0,0,config.name,{fontFamily:'Arial',fontSize:'8px',fontStyle:'bold',color:'#f3eee3'}).setOrigin(.5);this.nameplate.add([bg,label]);this.icon=scene.add.text(x,y-65,'',{fontFamily:'Arial',fontSize:'14px'}).setOrigin(.5).setDepth(y+120);this.selection=scene.add.ellipse(x,y+2,34,13,0xd8b26a,.15).setStrokeStyle(1,0xd8b26a,.8).setDepth(y-2).setVisible(false);this.sprite.on('pointerdown',()=>selectNpc(id,true));this.sprite.on('pointerover',()=>{scene.input.setDefaultCursor('pointer');this.nameplate.setScale(1.06)});this.sprite.on('pointerout',()=>{scene.input.setDefaultCursor('default');this.nameplate.setScale(1)});this.setMode('IDLE')}
    setSelected(selected){this.selection.setVisible(selected)}
    setMode(mode,label){this.mode=mode;if(label)this.activityLabel=label;this.icon.setText(mode==='WORKING'?'⌨':mode==='MEETING'?'◆':mode==='COFFEE'?'☕':mode==='WAITING_APPROVAL'?'!':mode==='BLOCKED'?'⚠':mode==='TALKING'?'…':'')}
    goTo(tile,label,mode='WALKING'){const current=this.scene.worldToTile(this.sprite.x,this.sprite.y);this.path=this.scene.grid.path(current,tile).slice(1);this.pathIndex=0;this.locationLabel=label;this.setMode(mode,label);if(!this.path.length)this.beginActivity(mode,label)}
    beginActivity(mode,label){this.setMode(mode,label);const durations={WORKING:6500,MEETING:5000,COFFEE:4200,TALKING:3800,WAITING_APPROVAL:10000,BLOCKED:7000,IDLE:2800};this.actionUntil=this.scene.time.now+(durations[mode]||3200);this.sprite.stop();this.sprite.setFrame(0);if(['WORKING','COFFEE','MEETING'].includes(mode))this.scene.tweens.add({targets:this.sprite,scaleX:1.58,scaleY:1.50,yoyo:true,repeat:2,duration:450})}
    applyJob(job,status){const changed=status!==this.lastStatus||job?.id!==this.operationalJob?.id;this.operationalJob=job;this.lastStatus=status;if(!changed)return;if(status==='WAITING_APPROVAL'){this.goTo(STATIONS.meetingA.tile,'PMO APPROVAL ROOM','WAITING_APPROVAL');showSpeech(this,'승인 검토를 기다리고 있습니다.')}else if(['BLOCKED','FAILED'].includes(status)){this.goTo(STATIONS.server.tile,'SUPPORT DESK','BLOCKED');showSpeech(this,'문제가 발생했습니다. 지원이 필요합니다.')}else if(ACTIVE.has(status)){this.goTo(this.config.desk,'WORKSTATION','WORKING');showSpeech(this,job?.title?job.title.slice(0,48):'업무를 시작합니다.')}else if(status==='COMPLETED'){this.goTo(STATIONS.loungeA.tile,'RESULT LOUNGE','TALKING');showSpeech(this,'업무 결과를 제출했습니다.')}}
    autonomousDecision(){if(this.operationalJob&&(ACTIVE.has(this.operationalJob.status)||this.operationalJob.status==='WAITING_APPROVAL'))return;const roleRoutes={pmo:['board','meetingA','coffee'],design:['board','coffee','loungeB'],dev:['server','coffee','printer'],sales:['meetingB','coffee','lobby'],product:['printer','board','coffee'],marketing:['loungeB','coffee','board'],finance:['printer','coffee','meetingB'],admin:['printer','lobby','coffee'],research:['board','loungeA','coffee'],audit:['server','board','coffee']},choices=roleRoutes[this.id]||['coffee','loungeA','printer'],key=Math.random()<.42?'desk':choices[Math.floor(Math.random()*choices.length)];if(key==='desk')this.goTo(this.config.desk,'WORKSTATION','WORKING');else{const station=STATIONS[key],mode=key==='coffee'?'COFFEE':key.startsWith('meeting')||key==='board'?'MEETING':key.startsWith('lounge')?'TALKING':'IDLE';this.goTo(station.tile,station.label,mode)}}
    update(time,delta){this.energy=Math.max(22,Math.min(100,this.energy+(this.mode==='COFFEE'?.012:this.mode==='WORKING'?-.003:.001)*delta));if(this.pathIndex<this.path.length){const[tx,ty]=this.path[this.pathIndex],[wx,wy]=this.scene.tileToWorld(tx,ty),dx=wx-this.sprite.x,dy=wy-this.sprite.y,dist=Math.hypot(dx,dy),speed=this.mode==='BLOCKED'?72:92;if(dist<3){this.sprite.setPosition(wx,wy);this.pathIndex++;if(this.pathIndex>=this.path.length)this.beginActivity(this.mode==='WALKING'?'IDLE':this.mode,this.activityLabel)}else{const step=Math.min(dist,speed*delta/1000);this.sprite.x+=dx/dist*step;this.sprite.y+=dy/dist*step;const dir=Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down'),key=`${this.id}-walk-${dir}`;if(this.sprite.anims.currentAnim?.key!==key)this.sprite.play(key,true)}}else if(time>this.actionUntil&&time>this.nextDecision){this.nextDecision=time+1500+Math.random()*2500;this.autonomousDecision()}this.sprite.setDepth(this.sprite.y+50);this.nameplate.setPosition(this.sprite.x,this.sprite.y-45).setDepth(this.sprite.y+100);this.icon.setPosition(this.sprite.x,this.sprite.y-65).setDepth(this.sprite.y+120);this.selection.setPosition(this.sprite.x,this.sprite.y+2).setDepth(this.sprite.y-2)}
  }

  class OfficeScene extends Phaser.Scene{
    constructor(){super('OfficeScene');this.npcs=new Map();this.selected=null;this.grid=new AStarGrid(COLS,ROWS);this.dragging=false;this.dragOrigin=null}
    create(){gameScene=this;this.cameras.main.setBackgroundColor('#0a0e12');this.buildGrid();this.drawOffice();Object.entries(ROLE_CONFIG).forEach(([id,config])=>{createAgentSheet(this,id,config);this.npcs.set(id,new NPC(this,id,config))});this.setupCamera();this.setupInput();this.input.mouse?.disableContextMenu();ui.loading.hidden=true;loadState();pollTimer=setInterval(()=>loadState(true),5000);selectNpc('pmo');this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>clearInterval(pollTimer))}
    buildGrid(){for(let x=0;x<COLS;x++){this.grid.block(x,0);this.grid.block(x,ROWS-1)}for(let y=0;y<ROWS;y++){this.grid.block(0,y);this.grid.block(COLS-1,y)};[[2,2,5,3],[8,2,4,3],[17,2,5,3],[22,2,4,4],[2,7,5,3],[8,7,5,3],[17,6,6,4],[2,12,5,3],[8,12,5,3],[18,12,4,3],[23,12,3,3]].forEach(r=>this.grid.block(...r));this.grid.block(12,3,4,2);this.grid.block(12,12,4,2)}
    tileToWorld(x,y){return[x*TILE+TILE/2,y*TILE+TILE/2]}
    worldToTile(x,y){return[Math.max(0,Math.min(COLS-1,Math.floor(x/TILE))),Math.max(0,Math.min(ROWS-1,Math.floor(y/TILE)))]}
    drawOffice(){const g=this.add.graphics();g.fillStyle(0x111820,1).fillRect(0,0,WORLD_W,WORLD_H);g.fillStyle(0x26323a,1).fillRect(TILE,TILE,WORLD_W-TILE*2,WORLD_H-TILE*2);for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++){const c=(x+y)%2?0x2d3a42:0x2a363e;g.fillStyle(c,1).fillRect(x*TILE,y*TILE,TILE,TILE);g.lineStyle(1,0xffffff,.025).strokeRect(x*TILE,y*TILE,TILE,TILE)}this.drawCarpet(g,11,1,6,10,0x253746);this.drawCarpet(g,1,11,15,5,0x28323a);this.drawCarpet(g,17,10,10,6,0x252d36);this.drawWalls(g);this.drawWindows(g);this.drawDepartment(g,2,2,5,3,0xb7654b);this.drawDepartment(g,8,2,4,3,0x4e84a8);this.drawDepartment(g,17,2,5,3,0x826cbb);this.drawDepartment(g,22,2,4,4,0x386c7a);this.drawDepartment(g,2,7,5,3,0xb34f73);this.drawDepartment(g,8,7,5,3,0x9c7b42);this.drawDepartment(g,17,6,6,4,0x466f9e);this.drawDepartment(g,2,12,5,3,0xa78a45);this.drawDepartment(g,8,12,5,3,0x678e48);this.drawDepartment(g,18,12,4,3,0x526c9d);this.drawDepartment(g,23,12,3,3,0xa35b61);this.drawMeeting(g,12,3);this.drawCoffee(g,12,12);this.drawLounge(g,22,7);this.drawServer(g,24,3);this.drawPlants(g);this.drawSigns();this.add.rectangle(WORLD_W/2,WORLD_H-18,WORLD_W-100,5,0xd8b26a,.25).setDepth(1)}
    drawCarpet(g,x,y,w,h,color){g.fillStyle(color,.92).fillRoundedRect(x*TILE,y*TILE,w*TILE,h*TILE,10);g.lineStyle(2,0xcaa760,.12).strokeRoundedRect(x*TILE,y*TILE,w*TILE,h*TILE,10)}
    drawWalls(g){g.fillStyle(0x0b1015,1);g.fillRect(0,0,WORLD_W,TILE);g.fillRect(0,WORLD_H-TILE,WORLD_W,TILE);g.fillRect(0,0,TILE,WORLD_H);g.fillRect(WORLD_W-TILE,0,TILE,WORLD_H);g.fillStyle(0x52606a,1).fillRect(TILE,TILE-7,WORLD_W-2*TILE,7);g.fillRect(TILE,WORLD_H-TILE,WORLD_W-2*TILE,7)}
    drawWindows(g){for(let x=2;x<27;x+=3){g.fillStyle(0x8ab4c7,.28).fillRect(x*TILE+4,10,TILE*2-8,26);g.lineStyle(2,0xb9d5df,.18).strokeRect(x*TILE+4,10,TILE*2-8,26);g.lineBetween((x+1)*TILE,10,(x+1)*TILE,36)}}
    drawDepartment(g,x,y,w,h,color){g.fillStyle(color,.08).fillRoundedRect(x*TILE,y*TILE,w*TILE,h*TILE,8);g.lineStyle(1,color,.35).strokeRoundedRect(x*TILE,y*TILE,w*TILE,h*TILE,8);this.drawDesk(g,x+1,y+1,w-2)}
    drawDesk(g,x,y,w){const px=x*TILE,py=y*TILE,width=Math.max(TILE*1.4,w*TILE);g.fillStyle(0x5a402b,1).fillRoundedRect(px,py,width,30,4);g.fillStyle(0x97704a,1).fillRect(px+3,py+3,width-6,5);g.fillStyle(0x172029,1).fillRoundedRect(px+12,py-18,34,24,3);g.fillStyle(0x4d7b91,.8).fillRect(px+16,py-14,26,14);g.fillStyle(0x1a2229,1).fillRect(px+24,py+6,10,7);g.fillStyle(0x1b232b,1).fillRoundedRect(px+12,py+35,28,25,5);g.fillStyle(0x45525c,1).fillRect(px+16,py+38,20,6)}
    drawMeeting(g,x,y){g.fillStyle(0x684c31,1).fillRoundedRect(x*TILE,y*TILE+4,4*TILE,2*TILE-8,30);g.fillStyle(0xaf8757,.55).fillRoundedRect(x*TILE+8,y*TILE+12,4*TILE-16,2*TILE-24,24);for(let i=0;i<4;i++){g.fillStyle(0x1d2730,1).fillRoundedRect((x+i)*TILE+10,y*TILE-12,28,24,5);g.fillRoundedRect((x+i)*TILE+10,(y+2)*TILE-12,28,24,5)}}
    drawCoffee(g,x,y){g.fillStyle(0x2a1f19,1).fillRoundedRect(x*TILE,y*TILE,4*TILE,2*TILE,8);g.fillStyle(0x806040,1).fillRect(x*TILE+10,y*TILE+10,4*TILE-20,28);g.fillStyle(0x172028,1).fillRoundedRect(x*TILE+22,y*TILE+4,34,28,4);g.fillStyle(0xd7b36a,.65).fillRect(x*TILE+28,y*TILE+11,22,4);for(let i=0;i<3;i++){g.fillStyle(0xf1eadc,.85).fillCircle((x+2+i*.45)*TILE,y*TILE+26,6)}}
    drawLounge(g,x,y){g.fillStyle(0x1a252d,1).fillRoundedRect(x*TILE,y*TILE,4*TILE,3*TILE,12);g.fillStyle(0x6d4c61,1).fillRoundedRect(x*TILE+12,y*TILE+20,3*TILE+12,45,10);g.fillStyle(0xb07b93,.35).fillRoundedRect(x*TILE+20,y*TILE+26,3*TILE-4,12,4);g.fillStyle(0x6d4b2c,1).fillRoundedRect(x*TILE+50,y*TILE+90,80,30,10)}
    drawServer(g,x,y){for(let i=0;i<2;i++){g.fillStyle(0x131a20,1).fillRoundedRect((x+i)*TILE+5,y*TILE,38,3*TILE,5);for(let j=0;j<7;j++){g.fillStyle(j%2?0x53bd79:0x4f8cc7,.75).fillCircle((x+i)*TILE+13,y*TILE+14+j*17,2);g.lineStyle(1,0x394650,1).strokeRect((x+i)*TILE+9,y*TILE+8+j*17,28,11)}}}
    drawPlants(g){[[1.4,5.5],[6.5,5.5],[16.5,5.2],[26.3,7],[16.5,14.5],[1.5,15]].forEach(([x,y])=>{g.fillStyle(0x6d5132,1).fillRect(x*TILE-8,y*TILE+7,16,14);g.fillStyle(0x4c8c5a,1).fillCircle(x*TILE,y*TILE,12);g.fillStyle(0x68a86c,.85).fillCircle(x*TILE-9,y*TILE+2,7);g.fillCircle(x*TILE+9,y*TILE+2,7)})}
    drawSigns(){const labels=[['SALES',4.5,1.55],['PRODUCT',10,1.55],['DESIGN',19.5,1.55],['ENGINEERING',24,1.55],['MARKETING',4.5,6.55],['PMO',10.5,6.55],['PROJECT LAB',20,5.55],['FINANCE',4.5,11.55],['ADMIN',10.5,11.55],['RESEARCH',20,11.55],['AUDIT',24.5,11.55]];labels.forEach(([text,x,y])=>this.add.text(x*TILE,y*TILE,text,{fontFamily:'Arial',fontSize:'9px',fontStyle:'bold',color:'#d7c393',stroke:'#10161b',strokeThickness:3}).setOrigin(.5).setDepth(5))}
    setupCamera(){const cam=this.cameras.main;cam.setBounds(0,0,WORLD_W,WORLD_H);cam.centerOn(WORLD_W/2,WORLD_H/2);cam.setZoom(Math.max(.68,Math.min(1.08,this.scale.height/WORLD_H*.96)));this.scale.on('resize',()=>cam.setZoom(Math.max(.68,Math.min(1.08,this.scale.height/WORLD_H*.96))))}
    setupInput(){this.input.on('pointerdown',pointer=>{if(pointer.rightButtonDown()||pointer.middleButtonDown()){this.dragging=true;this.dragOrigin={x:pointer.x,y:pointer.y,scrollX:this.cameras.main.scrollX,scrollY:this.cameras.main.scrollY}}});this.input.on('pointermove',pointer=>{if(this.dragging&&pointer.isDown){this.cameras.main.scrollX=this.dragOrigin.scrollX-(pointer.x-this.dragOrigin.x)/this.cameras.main.zoom;this.cameras.main.scrollY=this.dragOrigin.scrollY-(pointer.y-this.dragOrigin.y)/this.cameras.main.zoom}});this.input.on('pointerup',()=>this.dragging=false);this.input.on('wheel',(_p,_o,_dx,dy)=>{this.cameras.main.zoom=Phaser.Math.Clamp(this.cameras.main.zoom-dy*.0005,.58,1.4)})}
    setSelected(id){this.selected=id;this.npcs.forEach((npc,key)=>npc.setSelected(key===id))}
    focusAgent(id,pulse=false){const npc=this.npcs.get(id);if(!npc)return;this.cameras.main.pan(npc.sprite.x,npc.sprite.y,550,'Sine.easeInOut');if(pulse)this.tweens.add({targets:npc.selection,alpha:{from:.2,to:.85},scale:{from:.7,to:1.5},yoyo:true,repeat:2,duration:350});selectNpc(id)}
    applyOperationalState(state){this.npcs.forEach((npc,id)=>{const source=state.agents.find(agent=>agent.id===id),job=state.jobs.find(item=>item.owner_agent_id===id&&(ACTIVE.has(item.status)||item.status==='WAITING_APPROVAL'))||state.jobs.find(item=>item.owner_agent_id===id&&RESULTS.has(item.status)),status=job?.status||source?.status||'IDLE';npc.applyJob(job,status)})}
    update(time,delta){this.npcs.forEach(npc=>npc.update(time,delta));if(selectedNpcId)renderSelected()}
  }

  function startGame(){if(!window.Phaser){ui.loading.hidden=true;ui.error.hidden=false;return}new Phaser.Game({type:Phaser.AUTO,parent:'gameMount',backgroundColor:'#0a0e12',pixelArt:true,antialias:false,roundPixels:true,scale:{mode:Phaser.Scale.RESIZE,width:$('gameMount').clientWidth||960,height:$('gameMount').clientHeight||640},scene:[OfficeScene],render:{pixelArt:true,antialias:false,powerPreference:'high-performance'},fps:{target:60,forceSetTimeOut:false}})}
  $('commandForm').addEventListener('submit',submitCommand);setupTabs();$('zoomIn').addEventListener('click',()=>{if(gameScene)gameScene.cameras.main.zoom=Phaser.Math.Clamp(gameScene.cameras.main.zoom+.1,.58,1.4)});$('zoomOut').addEventListener('click',()=>{if(gameScene)gameScene.cameras.main.zoom=Phaser.Math.Clamp(gameScene.cameras.main.zoom-.1,.58,1.4)});$('zoomReset').addEventListener('click',()=>{if(gameScene){gameScene.cameras.main.centerOn(WORLD_W/2,WORLD_H/2);gameScene.cameras.main.zoom=Math.max(.68,Math.min(1.08,gameScene.scale.height/WORLD_H*.96))}});setInterval(()=>{ui.clock.textContent=new Date().toLocaleTimeString('ko-KR',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hour12:false})},1000);window.addEventListener('error',event=>{if(String(event.message||'').toLowerCase().includes('phaser')){ui.loading.hidden=true;ui.error.hidden=false}});startGame();
})();
