(() => {
  'use strict';

  const API = 'https://ckzwmimmwdnmpohgvcka.supabase.co/functions/v1/unity-ai-office-dev-open-v2';
  const ACTIVE = new Set(['QUEUED', 'APPROVED', 'RUNNING', 'WORKING']);
  const RESULTS = new Set(['COMPLETED', 'BLOCKED', 'FAILED', 'CANCELLED']);
  const VIEWS = new Set(['projects', 'agents', 'analytics', 'knowledge', 'resources', 'reports', 'settings']);
  const $ = id => document.getElementById(id);
  const dialog = $('sectionDialog'), dialogTitle = $('dialogTitle'), dialogContent = $('dialogContent');
  const templateSelect = $('templateSelect'), commandInput = $('commandInput');
  let snapshot = {agents:[],jobs:[],events:[],contexts:[],capabilities:[],templates:[],tool_policies:[],queue:0,approvals:0,settings:{},execution:{},usage_summary:{},budget_policy:{},credential_status:{}};
  let currentView = 'dashboard', loading = null;

  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const shortId = value => String(value ?? '').slice(0,8) || '—';
  function formatDate(value){if(!value)return'—';try{return new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Bangkok',hour12:false})}catch{return'—'}}
  async function api(path,options={}){const headers=new Headers(options.headers||{});if(options.body&&!headers.has('content-type'))headers.set('content-type','application/json');const response=await fetch(`${API}${path}`,{...options,headers,cache:'no-store'});const data=await response.json().catch(()=>({ok:false,error:`HTTP_${response.status}`}));if(!response.ok||data.ok===false)throw new Error(data.error||`HTTP_${response.status}`);return data}
  async function fetchState(force=false){if(loading&&!force)return loading;loading=api('/state').then(data=>{snapshot={...snapshot,...data};for(const key of ['agents','jobs','events','contexts','capabilities','templates','tool_policies'])snapshot[key]=Array.isArray(data[key])?data[key]:[];populateTemplates();return snapshot}).finally(()=>{loading=null});return loading}
  const activeJobs=()=>snapshot.jobs.filter(job=>ACTIVE.has(job.status));
  const approvalJobs=()=>snapshot.jobs.filter(job=>job.status==='WAITING_APPROVAL');
  const resultJobs=()=>snapshot.jobs.filter(job=>RESULTS.has(job.status));
  const currentJob=agentId=>snapshot.jobs.find(job=>job.owner_agent_id===agentId&&(ACTIVE.has(job.status)||job.status==='WAITING_APPROVAL'))||null;
  const latestJob=agentId=>snapshot.jobs.find(job=>job.owner_agent_id===agentId)||null;
  const outputText=job=>{const result=job?.result||{};return result.output_text||result.reason||job?.error_message||result.message||job?.payload?.description||job?.title||'—'};
  const capabilityName=key=>snapshot.capabilities.find(item=>item.capability_key===key)?.name||key||'—';
  function setActiveNav(view){document.querySelectorAll('.nav-item').forEach(button=>button.classList.toggle('active',button.dataset.view===view))}
  function showDialog(title,html){dialogTitle.textContent=title;dialogContent.innerHTML=html;if(!dialog.open)dialog.showModal()}
  function statGrid(items){return`<div class="ops-stat-grid">${items.map(([label,value])=>`<div class="ops-stat"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`).join('')}</div>`}
  const empty=message=>`<div class="ops-empty">${escapeHtml(message)}</div>`;
  function statusClass(status){if(['BLOCKED','FAILED','CANCELLED'].includes(status))return'danger';if(status==='WAITING_APPROVAL')return'waiting';if(status==='COMPLETED')return'complete';if(ACTIVE.has(status))return'active';return'idle'}
  function jobRows(jobs,limit=50){if(!jobs.length)return empty('표시할 업무가 없습니다.');return`<div class="ops-list">${jobs.slice(0,limit).map(job=>`<button type="button" class="ops-row" data-ops-job="${escapeHtml(job.id)}"><span class="ops-row-main"><strong>${escapeHtml(job.title||'업무')}</strong><small>#${escapeHtml(shortId(job.id))} · ${escapeHtml(job.owner_agent_id||'pmo')} · ${escapeHtml(capabilityName(job.capability_key))}</small></span><span class="ops-status ${statusClass(job.status)}">${escapeHtml(job.status||'IDLE')}</span></button>`).join('')}</div>`}
  function bindJobRows(root=dialogContent){root.querySelectorAll('[data-ops-job]').forEach(button=>button.addEventListener('click',()=>openJob(button.dataset.opsJob)))}
  function jobActions(job){const actions=[];if(job.status==='WAITING_APPROVAL')actions.push(['approve','승인','approve'],['reject','거부','reject']);if(['BLOCKED','FAILED','CANCELLED'].includes(job.status))actions.push(['retry','재시도','retry']);if(!actions.length)return'';return`<div class="ops-actions">${actions.map(([action,label,cls])=>`<button type="button" class="${cls}" data-ops-action="${action}" data-job-id="${escapeHtml(job.id)}">${label}</button>`).join('')}</div>`}
  function openJob(id){const job=snapshot.jobs.find(item=>String(item.id)===String(id));if(!job)return;showDialog('JOB DETAIL',`${statGrid([['STATUS',job.status||'—'],['OWNER',job.owner_agent_id||'pmo'],['CAPABILITY',capabilityName(job.capability_key)],['RISK',job.risk_level||'L1'],['CREATED',formatDate(job.created_at)],['UPDATED',formatDate(job.updated_at||job.created_at)]])}<section class="ops-section"><h3>${escapeHtml(job.title||'업무')}</h3><pre class="ops-report">${escapeHtml(outputText(job))}</pre></section>${jobActions(job)}`);bindActionButtons()}
  function bindActionButtons(){dialogContent.querySelectorAll('[data-ops-action]').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;try{await api(`/${button.dataset.opsAction}`,{method:'POST',body:JSON.stringify({job_id:button.dataset.jobId})});await fetchState(true);openView(currentView==='dashboard'?'projects':currentView,true)}catch(error){button.disabled=false;alert(`업무 상태 변경 실패: ${error.message}`)}}))}
  const projectKey=job=>job.project_id||job.payload?.project_id||job.payload?.project||job.capability_key||job.owner_agent_id||'GENERAL';
  function renderProjects(){const groups=new Map();for(const job of snapshot.jobs){const key=String(projectKey(job));if(!groups.has(key))groups.set(key,[]);groups.get(key).push(job)}const cards=[...groups.entries()].map(([key,jobs])=>{const active=jobs.filter(job=>ACTIVE.has(job.status)).length,completed=jobs.filter(job=>job.status==='COMPLETED').length,blocked=jobs.filter(job=>['BLOCKED','FAILED'].includes(job.status)).length;return`<button type="button" class="ops-project" data-project="${escapeHtml(key)}"><strong>${escapeHtml(capabilityName(key))}</strong><small>${jobs.length} JOBS · ACTIVE ${active} · COMPLETE ${completed} · ISSUE ${blocked}</small></button>`}).join('');showDialog('PROJECTS',`${statGrid([['PROJECT GROUPS',groups.size],['ACTIVE JOBS',activeJobs().length],['RESULTS',resultJobs().length],['APPROVAL',approvalJobs().length]])}<section class="ops-section"><h3>PROJECT / CAPABILITY GROUPS</h3><div class="ops-project-grid">${cards||empty('등록된 프로젝트 업무가 없습니다.')}</div></section><section id="opsProjectJobs" class="ops-section"><h3>RECENT JOBS</h3>${jobRows(snapshot.jobs,30)}</section>`);bindJobRows();dialogContent.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{const jobs=snapshot.jobs.filter(job=>String(projectKey(job))===button.dataset.project),target=$('opsProjectJobs');target.innerHTML=`<h3>${escapeHtml(capabilityName(button.dataset.project))}</h3>${jobRows(jobs,50)}`;bindJobRows(target)}))}
  function renderAgents(){const rows=snapshot.agents.map(agent=>{const job=currentJob(agent.id),latest=latestJob(agent.id),status=job?.status||agent.status||'IDLE';return`<button type="button" class="ops-row" data-agent="${escapeHtml(agent.id)}"><span class="ops-row-main"><strong>${escapeHtml(agent.name||agent.id)}</strong><small>${escapeHtml(agent.role||'AGENT')} · ${escapeHtml(job?.title||latest?.title||agent.current_task||'업무 대기')}</small></span><span class="ops-status ${statusClass(status)}">${escapeHtml(status)}</span></button>`}).join('');showDialog('AGENTS',`${statGrid([['TOTAL',snapshot.agents.length],['ACTIVE',snapshot.agents.filter(agent=>currentJob(agent.id)).length],['IDLE',snapshot.agents.filter(agent=>!currentJob(agent.id)).length],['ISSUES',resultJobs().filter(job=>['BLOCKED','FAILED'].includes(job.status)).length]])}<section class="ops-section"><h3>AGENT ROSTER</h3><div class="ops-list">${rows||empty('Agent 데이터가 없습니다.')}</div></section>`);dialogContent.querySelectorAll('[data-agent]').forEach(button=>button.addEventListener('click',()=>openAgent(button.dataset.agent)))}
  function openAgent(id){const agent=snapshot.agents.find(item=>item.id===id);if(!agent)return;const jobs=snapshot.jobs.filter(job=>job.owner_agent_id===id),job=currentJob(id);showDialog(agent.name||id.toUpperCase(),`${statGrid([['STATUS',job?.status||agent.status||'IDLE'],['ROLE',agent.role||'—'],['CURRENT TASK',job?.title||agent.current_task||'업무 대기'],['TOTAL JOBS',jobs.length],['COMPLETED',jobs.filter(item=>item.status==='COMPLETED').length],['ISSUES',jobs.filter(item=>['BLOCKED','FAILED'].includes(item.status)).length]])}<section class="ops-section"><h3>AGENT JOB HISTORY</h3>${jobRows(jobs,30)}</section>`);bindJobRows()}
  function eventRows(events){if(!events.length)return empty('기록된 이벤트가 없습니다.');return`<div class="ops-list">${events.map(event=>`<article class="ops-event"><strong>${escapeHtml(event.event_type||'EVENT')}</strong><small>${escapeHtml(event.message||'—')} · ${escapeHtml(event.agent_id||'SYSTEM')} · ${escapeHtml(formatDate(event.created_at))}</small></article>`).join('')}</div>`}
  function renderAnalytics(){const total=snapshot.jobs.length,completed=snapshot.jobs.filter(job=>job.status==='COMPLETED').length,issues=snapshot.jobs.filter(job=>['BLOCKED','FAILED'].includes(job.status)).length,completionRate=total?Math.round(completed/total*100):0,daily=snapshot.usage_summary?.daily||{},monthly=snapshot.usage_summary?.monthly||{},maxJobs=Math.max(1,...snapshot.agents.map(agent=>snapshot.jobs.filter(job=>job.owner_agent_id===agent.id).length)),workload=snapshot.agents.map(agent=>{const count=snapshot.jobs.filter(job=>job.owner_agent_id===agent.id).length;return`<div class="ops-meter"><span>${escapeHtml(agent.name||agent.id)}</span><i><b style="width:${Math.round(count/maxJobs*100)}%"></b></i><strong>${count}</strong></div>`}).join('');showDialog('ANALYTICS',`${statGrid([['TOTAL JOBS',total],['COMPLETION',`${completionRate}%`],['ACTIVE',activeJobs().length],['APPROVAL',approvalJobs().length],['ISSUES',issues],['DAILY TOKENS',Number(daily.total_tokens||0).toLocaleString()],['DAILY COST',`${Number(daily.estimated_cost_thb||0).toFixed(2)} THB`],['MONTH COST',`${Number(monthly.estimated_cost_thb||0).toFixed(2)} THB`]])}<section class="ops-section"><h3>AGENT WORKLOAD</h3><div class="ops-meters">${workload||empty('업무량 데이터가 없습니다.')}</div></section><section class="ops-section"><h3>RECENT EVENTS</h3>${eventRows(snapshot.events.slice(0,20))}</section>`)}
  function renderKnowledge(){const contexts=snapshot.contexts||[],rows=contexts.map(context=>`<article class="ops-event"><strong>${escapeHtml(context.context_key||context.name||'CONTEXT')}</strong><small>${escapeHtml((context.source_files||[]).join(' · ')||context.category||'Context')} · PRIORITY ${escapeHtml(context.priority??'—')} · ${escapeHtml(context.version||'—')}</small></article>`).join('');showDialog('KNOWLEDGE',`${statGrid([['CONTEXTS',contexts.length],['SOURCE FILES',contexts.reduce((sum,item)=>sum+(item.source_files?.length||0),0)],['ACTIVE CAPABILITIES',snapshot.capabilities.length],['TASK TEMPLATES',snapshot.templates.length]])}<section class="ops-section"><h3>CONTEXT REGISTRY</h3><div class="ops-list">${rows||empty('등록된 Knowledge Context가 없습니다.')}</div></section>`)}
  function renderResources(){const capabilities=snapshot.capabilities.map(item=>`<article class="ops-event"><strong>${escapeHtml(item.name||item.capability_key)}</strong><small>${escapeHtml(item.agent_id||'—')} · ${(item.allowed_tools||[]).map(escapeHtml).join(' · ')||'NO TOOLS'} · ${escapeHtml(item.risk_ceiling||'—')}</small></article>`).join(''),templates=snapshot.templates.map(item=>`<article class="ops-event"><strong>${escapeHtml(item.name||item.template_key)}</strong><small>${escapeHtml(item.agent_id||'—')} · ${escapeHtml(item.capability_key||'—')} · ${escapeHtml(item.risk_level||'—')}</small></article>`).join(''),policies=snapshot.tool_policies.map(item=>`<article class="ops-event"><strong>${escapeHtml(item.name||item.tool_key||'TOOL')}</strong><small>${item.enabled?'ENABLED':'DISABLED'} · ${escapeHtml(item.access_mode||'—')} · ${item.requires_approval?'APPROVAL REQUIRED':'NO APPROVAL'}</small></article>`).join('');showDialog('RESOURCES',`${statGrid([['CAPABILITIES',snapshot.capabilities.length],['TEMPLATES',snapshot.templates.length],['TOOL POLICIES',snapshot.tool_policies.length],['AGENTS',snapshot.agents.length]])}<section class="ops-section"><h3>CAPABILITY PACKAGES</h3><div class="ops-list">${capabilities||empty('Capability가 없습니다.')}</div></section><section class="ops-section"><h3>TASK TEMPLATES</h3><div class="ops-list">${templates||empty('Template이 없습니다.')}</div></section><section class="ops-section"><h3>TOOL POLICIES</h3><div class="ops-list">${policies||empty('Tool Policy가 없습니다.')}</div></section>`)}
  function buildReport(){const completed=snapshot.jobs.filter(job=>job.status==='COMPLETED'),issues=snapshot.jobs.filter(job=>['BLOCKED','FAILED'].includes(job.status)),approvals=approvalJobs(),lines=['# Unity Global AI Office Status Report','',`- Generated: ${formatDate(new Date().toISOString())}`,`- Agents: ${snapshot.agents.length}`,`- Active jobs: ${activeJobs().length}`,`- Waiting approval: ${approvals.length}`,`- Completed results: ${completed.length}`,`- Blocked / failed: ${issues.length}`,`- Scheduler: ${snapshot.settings?.workday_enabled?'ACTIVE':'PAUSED'}`,`- Model: ${snapshot.execution?.model_provider||'NONE'} / ${snapshot.execution?.model_name||'UNSET'}`,'','## Active Jobs',...(activeJobs().length?activeJobs().map(job=>`- [${job.status}] ${job.title} — ${job.owner_agent_id||'pmo'}`):['- None']),'','## Approval Queue',...(approvals.length?approvals.map(job=>`- ${job.title} — ${job.owner_agent_id||'pmo'}`):['- None']),'','## Recent Results',...(resultJobs().slice(0,15).length?resultJobs().slice(0,15).map(job=>`- [${job.status}] ${job.title} — ${String(outputText(job)).replace(/\s+/g,' ').slice(0,180)}`):['- None']),'','## Risks',...(issues.length?issues.map(job=>`- [${job.status}] ${job.title} — ${outputText(job)}`):['- None'])];return lines.join('\n')}
  function copyText(text){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text);const textarea=document.createElement('textarea');textarea.value=text;textarea.style.position='fixed';textarea.style.opacity='0';document.body.appendChild(textarea);textarea.select();document.execCommand('copy');textarea.remove();return Promise.resolve()}
  function downloadText(name,text,type='text/markdown;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function renderReports(){const report=buildReport();showDialog('REPORTS',`${statGrid([['RESULTS',resultJobs().length],['EVENTS',snapshot.events.length],['ISSUES',snapshot.jobs.filter(job=>['BLOCKED','FAILED'].includes(job.status)).length],['APPROVAL',approvalJobs().length]])}<div class="ops-actions"><button type="button" id="opsCopyReport">보고서 복사</button><button type="button" id="opsDownloadReport">Markdown 저장</button></div><pre class="ops-report" id="opsReportText">${escapeHtml(report)}</pre>`);$('opsCopyReport').addEventListener('click',async()=>{await copyText(report);$('opsCopyReport').textContent='복사 완료'});$('opsDownloadReport').addEventListener('click',()=>downloadText(`unity-ai-office-status-${new Date().toISOString().slice(0,10)}.md`,report))}
  function renderSettings(){const workday=Boolean(snapshot.settings?.workday_enabled),execution=snapshot.execution||{},budget=snapshot.budget_policy||{},credential=Boolean(snapshot.credential_status?.openai_configured);showDialog('SETTINGS',`${statGrid([['SCHEDULER',workday?'ACTIVE':'PAUSED'],['MODEL',`${execution.model_provider||'NONE'} / ${execution.model_name||'UNSET'}`],['MODEL STATUS',execution.model_enabled?'ENABLED':'BLOCKED'],['CREDENTIAL',credential?'CONFIGURED':'NOT SET'],['TOOLS',execution.tool_execution_enabled?'ENABLED':'DISABLED'],['HARD STOP',budget.hard_stop?'ON':'OFF'],['DAILY LIMIT',`${budget.daily_cost_limit_thb??'UNSET'} THB`],['ACCESS',snapshot.access_mode||'DEVELOPMENT']])}<section class="ops-section"><h3>OPERATION CONTROLS</h3><div class="ops-actions"><button type="button" id="opsScheduler" class="${workday?'reject':'approve'}">${workday?'스케줄러 중지':'스케줄러 활성화'}</button><button type="button" id="opsRefresh">상태 새로고침</button><button type="button" id="opsExportJson">운영 데이터 저장</button></div></section><section class="ops-section"><h3>DESIGN CUSTOMIZATION</h3><p class="ops-note">기능 구현 완료 후 색상, 폰트, 패널, 버튼, 맵, 캐릭터를 항목별 설정으로 분리합니다. 현재 단계에서는 디자인 값을 변경하지 않습니다.</p></section>`);$('opsScheduler').addEventListener('click',async event=>{event.currentTarget.disabled=true;try{await api('/admin/workday',{method:'POST',body:JSON.stringify({enabled:!workday})});await fetchState(true);renderSettings()}catch(error){event.currentTarget.disabled=false;alert(`스케줄러 변경 실패: ${error.message}`)}});$('opsRefresh').addEventListener('click',async event=>{event.currentTarget.disabled=true;await fetchState(true);renderSettings()});$('opsExportJson').addEventListener('click',()=>downloadText(`unity-ai-office-data-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(snapshot,null,2),'application/json;charset=utf-8'))}
  function populateTemplates(){if(!templateSelect)return;const selected=templateSelect.value,dynamic=snapshot.templates.map(template=>{const command=template.command_template||template.command||template.name||template.template_key;return`<option value="${escapeHtml(command)}" data-template-key="${escapeHtml(template.template_key||'')}">${escapeHtml(template.name||template.template_key)} · ${escapeHtml(template.agent_id||'PMO')}</option>`}).join(''),fallback='<option value="태국 시장 경쟁사 조사를 진행하고 핵심 결과를 보고해라">시장 조사</option><option value="현재 프로젝트 상태를 점검하고 위험 요소와 다음 실행안을 보고해라">프로젝트 점검</option><option value="최근 업무 결과를 검증하고 오류가 있으면 수정안을 제시해라">업무 검증</option>';templateSelect.innerHTML=`<option value="">직접 지시 / 업무 템플릿 선택</option>${dynamic||fallback}`;if([...templateSelect.options].some(option=>option.value===selected))templateSelect.value=selected}
  async function openView(view,force=false){if(!VIEWS.has(view))return;currentView=view;setActiveNav(view);showDialog(view.toUpperCase(),'<div class="ops-loading">운영 데이터를 불러오는 중입니다.</div>');try{await fetchState(force);if(view==='projects')renderProjects();else if(view==='agents')renderAgents();else if(view==='analytics')renderAnalytics();else if(view==='knowledge')renderKnowledge();else if(view==='resources')renderResources();else if(view==='reports')renderReports();else if(view==='settings')renderSettings()}catch(error){showDialog(view.toUpperCase(),empty(`데이터를 불러오지 못했습니다: ${error.message}`))}}
  document.addEventListener('click',event=>{const button=event.target.closest('.nav-item');if(!button)return;const view=button.dataset.view;event.preventDefault();event.stopImmediatePropagation();if(view==='dashboard'){currentView='dashboard';setActiveNav('dashboard');if(dialog.open)dialog.close();return}openView(view)},true);
  dialog.addEventListener('close',()=>{currentView='dashboard';setActiveNav('dashboard')});
  templateSelect?.addEventListener('change',()=>{if(templateSelect.value&&commandInput&&!commandInput.value.trim())commandInput.value=templateSelect.value});
  fetchState().catch(()=>{});
})();
