plugins {
    id 'com.android.application'
}

android {
    namespace 'com.unityglobal.unity_drive_access'
    compileSdk 35

    defaultConfig {
        applicationId 'com.unityglobal.unity_drive_access'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.0.3'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
}
